### ISSUE TITLE
Price increment is incorrect

### ISSUE THREAD

**Issue by anxolin** [gnosis/dx-services-admin#16]
For example, in this case, is showing that is positive increment, but the price is way below the previous market price. You can tell also because it's been running for 12 hours

<img width="1160" alt="Screenshot at May 12 13-13-47" src="https://user-images.githubusercontent.com/2352112/57612631-7bca7500-7575-11e9-956c-cd5469e762d8.png">

**Comment by W3stside** [comment]
@anxolin this one was fixed no? It doesn't seem wrong to me at first glance

**Comment by anxolin** [comment]
It's not solved. Look at this example of this market of Rinkeby:

![image](https://user-images.githubusercontent.com/2352112/59094265-0d7b9700-8916-11e9-9c08-fcbee836e1dc.png)

**Comment by W3stside** [comment]
not sure how to fix it as I think you edited the function, but i'll take a look later

**Comment by W3stside** [comment]
closed by #35
